name: charityapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  get: ^4.3.8
  flutter_bloc: ^8.0.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  build_runner: ^2.1.7
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  path: ^1.8.0
  firebase_storage: ^11.0.10
  copy_with_extension: ^5.0.0
  flat_icons_flutter: ^1.0.2
  flutter_speed_dial: ^6.2.0
  fancy_dialog: ^1.0.4
  table_calendar: ^3.0.3
  material_floating_search_bar: ^0.3.6

 
  auto_size_text: ^3.0.0
  infinite_listview: ^1.1.0
  firebase_auth: ^4.2.5
  skeleton_loader: ^2.0.0+4
  implicitly_animated_reorderable_list: ^0.4.2
  animations: ^2.0.2
  email_auth: ^1.0.0
  rxdart: ^0.27.3
  tiengviet: ^0.5.0
  collection: ^1.15.0
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.2
  google_place: ^0.4.3
  flutter_typeahead: ^3.2.4
  geocoding: ^2.0.1
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.0
  page_transition: ^2.0.4
  spincircle_bottom_bar: ^2.0.0
  flutter_spinkit: ^5.1.0
  liquid_progress_indicator: ^0.4.0
  flutter_image_compress: ^1.1.0
  flutter_screenutil: ^5.1.0
  google_sign_in: ^5.2.3
  percent_indicator: ^4.2.1
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  json_serializable: ^6.1.0
  copy_with_extension_gen: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "asset/logo.png"

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/login.png
    - asset/splash2.png
    - asset/logo.png
    - asset/background.png
    - asset/welcome.png
    - asset/Icon/CalendarFullIcon.png
    - asset/Icon/CalendarIcon.png
    - asset/Icon/FriendFullIcon.png
    - asset/Icon/FriendIcon.png
    - asset/Icon/CalendarFullIcon.png
    - asset/Icon/HomeFullIcon.png
    - asset/Icon/HomeIcon.png
    - asset/Icon/NewFullIcon.png
    - asset/Icon/NewIcon.png
    - asset/Icon/ProfileFullIcon.png
    - asset/Icon/ProfileIcon.png
    - asset/Icon/Notice.png
    - asset/imagesample/post1.jpg
    - asset/imagesample/avatar1.jpg
    - asset/avatar.png
    - asset/imagesample/ImageAlerDIalog/wrong.png
    - asset/imagesample/ImageAlerDIalog/lostconnect.png
    - asset/imagesample/ImageAlerDIalog/updateprofile.png
    - asset/imagesample/ImageAlerDIalog/changepasssuccess.png
    - asset/imageInpage/no_result.png
    - asset/imageInpage/no_comment.png
    - asset/imageInpage/heart.png
    - asset/imageInpage/success.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Roboto_thin
      fonts:
         - asset: fonts/Roboto-Thin.ttf
    - family: Roboto_Regular
      fonts:
         - asset: fonts/Roboto-Regular.ttf
    - family: DancingScript_Regular
      fonts:
         - asset: fonts/DancingScript-Regular.ttf
    - family: Redressed_Regular
      fonts:
         - asset: fonts/Redressed-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
